INSERT INTO products (title, price, description, display_image) VALUES ('Crocodile Cards', 24.95, 'A complete set of Crocodile playing cards', 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338055/croc-deck-back_g9yr3t.png');
INSERT INTO product_images (product_id, image_url, is_display_image) VALUES (1, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338055/croc-deck-back_g9yr3t.png', TRUE);
INSERT INTO product_images (product_id, image_url, is_display_image) VALUES (1, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338056/croc-deck-front_gwaawo.png', FALSE);
INSERT INTO product_images (product_id, image_url, is_display_image) VALUES (1, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338049/croc-deck-action_v77zbe.png', FALSE);
INSERT INTO products (title, price, description, display_image) VALUES ('Crocodile Dealer Token', 9.95, 'A Crocodile Dealer chip so you can always keep track of whose turn it is to deal', './images/products/croc-dealer-token-front.png');
INSERT INTO product_images (product_id, image_url, is_display_image) VALUES (2, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338054/croc-dealer-token-front_srzesg.png', TRUE);
INSERT INTO product_images (product_id, image_url, is_display_image) VALUES (2, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338054/croc-dealer-token-back_htbuty.png', FALSE);
INSERT INTO product_images (product_id, image_url, is_display_image) VALUES (2, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338067/croc-dealer-token-action_dlk3hf.png', FALSE);
INSERT INTO products (title, price, description, display_image) VALUES ('Crocodile Hoodie', 49.95, 'A stylish Crocodile Hoodie, a signal to potential rivals of the billabong', 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338058/croc-hoodie-green-front_oqqs5l.png');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'Green', 'Small');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'Green', 'Medium');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'Green', 'Large');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'Green', 'XL');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (3, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338058/croc-hoodie-green-front_oqqs5l.png', 'Green', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (3, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338825/croc-hoodie-green-back_ljy5lk.png', 'Green', FALSE);
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'White', 'Small');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'White', 'Medium');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'White', 'Large');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'White', 'XL');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (3, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338059/croc-hoodie-white-front_fb5opa.png', 'White', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (3, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338061/croc-t-shirt-white-back_qx5vkd.png', 'White', FALSE);
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'Black', 'Small');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'Black', 'Medium');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'Black', 'Large');
INSERT INTO product_variants (product_id, color, size) VALUES (3, 'Black', 'XL');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (3, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338056/croc-hoodie-black-front_egoo8d.png', 'Black', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (3, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338056/croc-hoodie-black-back_f1ryst.png', 'Black', FALSE);
INSERT INTO products (title, price, description, display_image) VALUES ('Crocodile T-Shirt', 29.95, 'A A stylish Crocodile T-shirt, a signal to potential rivals of the billabong', 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338049/croc-t-shirt-green-front_t6pd6c.png');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'Green', 'Small');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'Green', 'Medium');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'Green', 'Large');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'Green', 'XL');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (4, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338049/croc-t-shirt-green-front_t6pd6c.png', 'Green', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (4, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338062/croc-t-shirt-green-back_ol9sgi.png', 'Green', FALSE);
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'White', 'Small');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'White', 'Medium');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'White', 'Large');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'White', 'XL');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (4, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338050/croc-t-shirt-white-front_ns7hhd.png', 'White', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (4, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338061/croc-t-shirt-white-back_qx5vkd.png', 'White', FALSE);
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'Black', 'Small');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'Black', 'Medium');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'Black', 'Large');
INSERT INTO product_variants (product_id, color, size) VALUES (4, 'Black', 'XL');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (4, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338060/croc-t-shirt-black-front_hk8msh.png', 'Black', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (4, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338059/croc-t-shirt-black-back_f6t2xs.png', 'Black', FALSE);
INSERT INTO products (title, price, description, display_image) VALUES ('Crocodile Cap', 24.95, 'A fresh corduroy Crocodile Cap', 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338051/croc-cap-green-front_nkxfau.png');
INSERT INTO product_variants (product_id, color) VALUES (5, 'Green');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (5, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338051/croc-cap-green-front_nkxfau.png', 'Green', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (5, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338051/croc-cap-green-back_ov7q2x.png', 'Green', FALSE);
INSERT INTO product_variants (product_id, color) VALUES (5, 'White');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (5, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338053/croc-cap-white-front_otc6gf.png', 'White', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (5, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338053/croc-cap-white-back_ual2yv.png', 'White', FALSE);
INSERT INTO product_variants (product_id, color) VALUES (5, 'Black');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (5, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338050/croc-cap-black-front_a5c6pv.png', 'Black', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (5, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338045/croc-cap-black-back_qwjh5j.png', 'Black', FALSE);
INSERT INTO products (title, price, description, display_image) VALUES ('Crocodile Beanie', 24.95, 'A A stylish Crocodile beanie, to keep you warm during hibernation', 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338055/croc-beanie-green-front_iypuet.png');
INSERT INTO product_variants (product_id, color) VALUES (6, 'Green');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (6, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338055/croc-beanie-green-front_iypuet.png', 'Green', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (6, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338048/croc-beanie-green-back_shoeci.png', 'Green', FALSE);
INSERT INTO product_variants (product_id, color) VALUES (6, 'White');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (6, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338063/croc-beanie-white-front_qnbhpu.png', 'White', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (6, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338057/croc-beanie-white-back_fvtvmj.png', 'White', FALSE);
INSERT INTO product_variants (product_id, color) VALUES (6, 'Black');
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (6, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338047/croc-beanie-black-front_j7nj9k.png', 'Black', TRUE);
INSERT INTO product_images (product_id, image_url, color, is_display_image) VALUES (6, 'https://res.cloudinary.com/dm8swax4s/image/upload/v1753338047/croc-beanie-black-back_d44rtk.png', 'Black', FALSE);
